baseURL: "https://barnabeledoux.github.io" 
title: Barnabe Ledoux
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20


output: 
  xaringan::moon_reader:
    seal: false
    
taxonomies:
    tag: tags

menu:
    main:
        - name: Presentation
          url: presentation/
          weight: 1
        - name: Publications
          url: publications/
          weight: 2
        - name: Posters
          url: posters/
          weight: 3
        - name: Talks
          url: talks/
          weight: 4

params:
    description: "This website hosts Barnabe Ledoux's research papers, curriculum vitae, lectures and contact information."
    author: Barnabe Ledoux
    DateFormat: "January 2025"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["presentation","publications","posters","talks"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
        enabled: true
        title: Barnabe Ledoux
        subtitle: "PhD candidate in physics at the Gulliver Laboratory in ESPCI, with David Lacoste, on the topic “Growth in uncertain environments”. My curriculum
          includes courses in statistical physics, biophysics and physics of complex systems. I am particularly keen to integrate environmental
          considerations into my training, and hope to reconcile my research with these concerns during my PhD. I work at the frontier between physics and 
          biology, but also economics."
        imageUrl: "photo2.jpeg"
        imageWidth: 160
        imageHeight: 160
        backgroundClass: "profile-frame" # Add a custom class
        buttons:
          - name: Presentation
            url: presentation/
          - name: Publications
            url: publications/
          - name: Posters
            url: posters/
          - name: Talks
            url: talks/

    socialIcons:
        - name: CV
          url: CV_Barnabe_Ledoux.pdf
        - name: Email
          url: mailto:barnabe.ledoux@espci.fr
        #- name: Zoom
        #  url: https://www.zoom.us/my/igelfeld
        #- name: Location
        #  url: location/
        #- name: Office Hours
        #  url: officehours/
        #- name: Google Scholar
        #  url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        #- name: GitHub
        #  url: https://github.com/pmichaillat
        - name: Linkedin
          url: https://www.linkedin.com/in/barnabé-ledoux
        - name: ORCID
          url: https://orcid.org/0009-0005-1072-5886

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Barnabe Ledoux"
      icon: icon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2